one = raw_input("Enter a plural noun: ")
two = raw_input("Enter a place: ")
three = raw_input("Enter a noun: ")
four = raw_input("Enter a plural noun: ")
five = raw_input("Enter a noun: ")
six = raw_input("Enter an adjective: ")
seven = raw_input("Enter a verb: ")
eight = raw_input("Enter a number: ")
nine = raw_input("Enter an adjective: ")
ten = raw_input("Enter a body part: ")
eleven = raw_input("Enter a verb: ")

print("*_______________________________________________________________________*")
print("| Two "+one+", both alike in dignity,                                   |")
print("| In fair "+two+", where we lay our scene,                              |")
print("| From ancient "+three+" break to new mutiny,                           |")
print("| Where civil blood makes civil hands unclean.                          |")
print("| From forth the fatal loins of these two foes                          |")
print("| A pair of star-cross`d "+four+" take their life;                      |")
print("| Whole misadventured piteous overthrows                                |")
print("| Do with their "+five+" bury their parents` strife.                    |")
print("| The fearful passage of their "+six+" love,                            |")
print("| And the continuance of their parents` rage,                           |")
print("| Which, but their children`s end, nought could "+seven+",              |")
print("| Is now the "+eight+" hours` traffic of our stage;                     |")
print("| The which if you with "+nine+" "+ten+" attend,                        |")
print("| What here shall "+eleven+", our toil shall strive to mend.            |")
print("*_______________________________________________________________________*")
print("Romeo and Juliet Prologue Source: https://www.madtakes.com/libs/186.html")
