from termcolor import colored, cprint

one = raw_input("Enter a plural noun: ")
two = raw_input("Enter a place: ")
three = raw_input("Enter a noun: ")
four = raw_input("Enter a plural noun: ")
five = raw_input("Enter a noun: ")
six = raw_input("Enter an adjective: ")
seven = raw_input("Enter a verb: ")
eight = raw_input("Enter a number: ")
nine = raw_input("Enter an adjective: ")
ten = raw_input("Enter a body part: ")
eleven = raw_input("Enter a verb: ")

print("*_______________________________________________________________________*")
print("  Two "+colored(one, attrs=['bold'])+", both alike in dignity,")
print("  In fair "+colored(two, attrs=['bold'])+", where we lay our scene,")
print("  From ancient "+colored(three, attrs=['bold'])+" break to new mutiny,")
print("  Where civil blood makes civil hands unclean.")
print("  From forth the fatal loins of these two foes")
print("  A pair of star-cross`d "+colored(four, attrs=['bold'])+" take their life;")
print("  Whole misadventured piteous overthrows")
print("  Do with their "+colored(five, attrs=['bold'])+" bury their parents` strife.")
print("  The fearful passage of their "+colored(six, attrs=['bold'])+" love,")
print("  And the continuance of their parents` rage,")
print("  Which, but their children`s end, nought could "+colored(seven, attrs=['bold'])+",")
print("  Is now the "+colored(eight, attrs=['bold'])+" hours` traffic of our stage;")
print("  The which if you with "+colored(nine, attrs=['bold'])+" "+colored(ten, attrs=['bold'])+" attend,")
print("  What here shall "+colored(eleven, attrs=['bold'])+", our toil shall strive to mend.")
print("*_______________________________________________________________________*")
print("Romeo and Juliet Prologue Source: https://www.madtakes.com/libs/186.html")
